clear all;clc;close all;
addpath('../../../lib/');
resetpath;
addpath('./');
addpath('../');
addpath(genpath('../../../lib/abstr-ref/'));
addpath('../../../lib/GridGener/');
addpath('../../../lib/Parallel/');
addpath('../../../lib/SimuAndAnim/');
addpath('../../../lib/GroundGener/');